#-----------------------/*
#	helix main theme
#-----------------------*/

"escape" = "red"
"type" = "foreground"
"constant" = "foreground"
"number" = "foreground"
"string" = "foreground"
"comment" = "grey"
"variable" = "foreground"
"variable.builtin" = "red"
"variable.parameter" = "foreground"
"variable.property" = "foreground"
"label" = "blue"
"punctuation" = "foreground"
"punctuation.delimiter" = "foreground"
"punctuation.bracket" = "foreground"
"keyword" = "red"
"operator" = "foreground"
"function" = "foreground"
"function.builtin" = "blue"
"function.macro" = "blue"
"tag" = "blue"
"namespace" = "red"
"attribute" = "blue"
"constructor" = "red"
"module" = "red"
"property" = "foreground"
"special" = "red"

"ui.background" = { bg = "background" }
"ui.cursor" = { fg = "background", bg = "foreground" }
"ui.cursor.match" = { fg = "background", bg = "foreground" }
"ui.cursor.insert" = { fg = "background", bg = "foreground" }
"ui.cursor.select" = { fg = "background", bg = "foreground" }
"ui.linenr" = "foreground"
"ui.linenr.selected" = { fg = "red", modifiers = ["bold", "underlined"] }
"ui.statusline" = { fg = "foreground", bg = "background-alt" }
"ui.statusline.inactive" = { fg = "foreground", bg = "background-alt" }
"ui.popup" = { fg = "foreground", bg = "background-alt" }
"ui.window" = { fg = "foreground", bg = "background-alt" }
"ui.help" = { fg = "foreground", bg = "background-alt" }
"ui.text" = "foreground"
"ui.text.focus" = "red"
"ui.menu" = { fg = "foreground", bg = "background-alt" }
"ui.menu.selected" = { fg = "background", bg = "red" }
"ui.selection" = { bg = "background-alt" }

"hint" = "blue"
"info" = "foreground"
"warning" = "red"
"error" = "red"
"diagnostic" = { fg = "red", Modifiers = ["underlined"] }

[palette]
background = "#323437"
background-alt = "#55585e"
foreground = "#d1d0c5"

red = "#d75f5f"
blue = "#5f87ff" 
grey = "#5f87ff"

